Emorenoo patch 1
emorenoo/rest-assured-workshop pull request #9
Opened 2023-07-21 16:03 UTC by emorenoo

2023-07-26 23:32 UTC, dairoquinteroc commented on allure-results/64a7cd00-5272-4d46-9757-d631da79a5a1-attachment.html
> +    <pre class="preformated-text">
Don't include this report files

2023-07-26 23:32 UTC, dairoquinteroc commented on allure-results/673649ff-9ca3-4d3e-921a-5ab43f5fd432-attachment.html
> +        <div>X-Amz-Cf-Id: Pgw8Vtdy7hSvdcWkOLfHR8vPycpnjEG2LhiNIlZvavNKITXNLaezoQ==</div>
Don't include this report files

2023-07-26 23:35 UTC, dairoquinteroc requested changes
Ok, delete the report files, don't include them in the PR

2023-07-27 23:17 UTC, emorenoo commented on allure-results/64a7cd00-5272-4d46-9757-d631da79a5a1-attachment.html
> +    <pre class="preformated-text">
I have deleted all reports files.

2023-07-27 23:17 UTC, emorenoo commented on allure-results/673649ff-9ca3-4d3e-921a-5ab43f5fd432-attachment.html
> +        <div>X-Amz-Cf-Id: Pgw8Vtdy7hSvdcWkOLfHR8vPycpnjEG2LhiNIlZvavNKITXNLaezoQ==</div>
I have deleted all reports files.

2023-07-28 14:48 UTC, dairoquinteroc approved these changes
Great!

2023-07-28 15:51 UTC, merged